import KeyCode from "./classes/keyCode";

const keyCodes = {
    CANCEL: new KeyCode('0x03', 3, 'Cancel', 'The cancel key.'),
    HELP: new KeyCode('0x06', 6, 'Help', 'The help key.'),
    BACKSPACE: new KeyCode('0x08', 8, 'Backspace', 'The backspace key.'),
    TAB: new KeyCode('0x09', 9, 'Tab', 'The tab key.'),
    CLEAR: new KeyCode('0x12', 12, 'Clear', '"5" key on Numpad when NumLock is unlocked. Or on Mac, clear key which is positioned at NumLock key.'),
    RETURN: new KeyCode('0x0D', 13, 'Enter', 'The enter or return key.'),
    ENTER: new KeyCode('0x0D', 13, 'Enter', 'The enter or return key.'),
    SHIFT: new KeyCode('0x10', 16, 'Shift', 'One of the shift keys.'),
    CONTROL: new KeyCode('0x11', 17, 'Control', 'One of the control keys.'),
    ALT: new KeyCode('0x12', 18, 'Alt', 'The alt or option key.'),
    PAUSE: new KeyCode('0x13', 19, 'Pause', 'The pause key.'),
    CAPS_LOCK: new KeyCode('0x14', 20, 'Caps Lock', 'The caps lock key.'),

    KANA: new KeyCode('0x15', 21, 'Kana'),
    HANGUL: new KeyCode('0x15', 21, 'Hangul'),
    EISU: new KeyCode('0x16', 22, 'Esiu'),
    JUNJA: new KeyCode('0x17', 23, 'Junja'),
    FINAL: new KeyCode('0x18', 24, 'Final'),
    HANJA: new KeyCode('0x19', 25, 'Hanja'),
    KANJI: new KeyCode('0x20', 26, 'Kanji'),

    ESCAPE: new KeyCode('0x1B', 27, 'Escape', 'The escape key.'),
    CONVERT: new KeyCode('0x1C', 28, 'Convert'),
    NONCONVERT: new KeyCode('0x1D', 29, 'Nonconvert'),
    ACCEPT: new KeyCode('0x1E', 30, 'Accept'),
    MODE_CHANGE: new KeyCode('0x1F', 31, 'Mode Change'),
    SPACE: new KeyCode('0x20', 32, 'Space', 'The space bar.'),
    PAGE_UP: new KeyCode('0x21', 33, 'Page Up', 'The page up key.'),
    PAGE_DOWN: new KeyCode('0x22', 34, 'Page Down', 'The page down key.'),
    END: new KeyCode('0x23', 35, 'End', 'The end key.'),
    HOME: new KeyCode('0x24', 36, 'Home', 'The home key.'),

    // Arrow Keys
    LEFT: new KeyCode('0x25', 37, 'Left', 'The left arrow.'),
    UP: new KeyCode('0x26', 38, 'Up', 'The up arrow.'),
    RIGHT: new KeyCode('0x27', 39, 'Right', 'The right arrow.'),
    DOWN: new KeyCode('0x28', 40, 'Down', 'The down arrow.'),

    SELECT: new KeyCode('0x29', 41, 'Select'),
    PRINT: new KeyCode ('0x2A', 42, 'Print'),
    EXECUTE: new KeyCode('0x2B', 43, 'Execute'),
    PRINT_SCREEN: new KeyCode('0x2C', 44, 'Print Screen', 'The print screen key.'),
    INSERT: new KeyCode('0x2D', 45, 'Insert', 'The Ins(ert) key.'),
    DELETE: new KeyCode('0x2E', 46, 'Delete', 'The del(ete) key.'),

    // Standard Number Keys
    0: new KeyCode('0x30', 48, '0', 'The 0 key in the "standard" location.'),
    1: new KeyCode('0x31', 49, '1', 'The 1 key in the "standard" location.'),
    2: new KeyCode('0x32', 50, '2', 'The 2 key in the "standard" location.'),
    3: new KeyCode('0x33', 51, '3', 'The 3 key in the "standard" location.'), 
    4: new KeyCode('0x34', 52, '4', 'The 4 key in the "standard" location.'),
    5: new KeyCode('0x35', 53, '5', 'The 5 key in the "standard" location.'),
    6: new KeyCode('0x36', 54, '6', 'The 6 key in the "standard" location.'),
    7: new KeyCode('0x37', 55, '7', 'The 7 key in the "standard" location.'),
    8: new KeyCode('0x38', 56, '8', 'The 8 key in the "standard" location.'),
    9: new KeyCode('0x39', 57, '9', 'The 9 key in the "standard" location.'),

    COLON: new KeyCode('0x3A', 58, 'Colon', 'The colon key.'),
    SEMICOLON: new KeyCode('0x3B', 59, 'Semicolon', 'The semicolon key.'),
    LESS_THAN: new KeyCode('0x3C', 60, 'Less Then', 'The less than (<) key.'),
    EQUALS: new KeyCode('0x3D', 61, 'Equals', 'The equals (=) key.'),
    GREATER_THAN: new KeyCode('0x3E', 62, 'Greater Than', 'The greater than (>) key.'),
    QUESTION_MARK: new KeyCode('0x3F', 63, 'Question Mark', 'The question mark (?) key.'),
    AT: new KeyCode('0x40', 64, 'Atmark', 'The atmark (@) key.'),

    // Letter Keys
    A: new KeyCode('0x41', 65, 'A', 'The A key.'),
    B: new KeyCode('0x42', 66, 'B', 'The B key.'),
    C: new KeyCode('0x43', 67, 'C', 'The C key.'),
    D: new KeyCode('0x44', 68, 'D', 'The D key.'),
    E: new KeyCode('0x45', 69, 'E', 'The E key.'),
    F: new KeyCode('0x46', 70, 'F', 'The F key.'),
    G: new KeyCode('0x47', 71, 'G', 'The G key.'),
    H: new KeyCode('0x48', 72, 'H', 'The H key.'),
    I: new KeyCode('0x49', 73, 'I', 'The I key.'),
    J: new KeyCode('0x4A', 74, 'J', 'The J key.'),
    K: new KeyCode('0x4B', 75, 'K', 'The K key.'),
    L: new KeyCode('0x4C', 76, 'L', 'The L key.'),
    M: new KeyCode('0x4D', 77, 'M', 'The M key.'),
    N: new KeyCode('0x4E', 78, 'N', 'The N key.'),
    O: new KeyCode('0x4F', 79, 'O', 'The O key.'),
    P: new KeyCode('0x50', 80, 'P', 'The P key.'),
    Q: new KeyCode('0x51', 81, 'Q', 'The Q key.'),
    R: new KeyCode('0x52', 82, 'R', 'The R key.'),
    S: new KeyCode('0x53', 83, 'S', 'The S key.'),
    T: new KeyCode('0x54', 84, 'T', 'The T key.'),
    U: new KeyCode('0x55', 85, 'U', 'The U key.'),
    V: new KeyCode('0x56', 86, 'V', 'The V key.'),
    W: new KeyCode('0x57', 87, 'W', 'The W key.'),
    X: new KeyCode('0x58', 88, 'X', 'The X key.'),
    Y: new KeyCode('0x59', 89, 'Y', 'The Y key.'),
    Z: new KeyCode('0x5A', 90, 'Z', 'The Z key.'),

    WIN: new KeyCode('0x5B', 91, 'Windows Key', 'The Windows key on Windows, Super on Mac, or Hyper on Linux.'),
    CONTEXT_MENU: new KeyCode('0x5D', 93, 'Context Menu', 'The context menu key.'),
    SLEEP: new KeyCode('0x5F', 95, 'Sleep'),

    // Numpad Keys
    NUMPAD0: new KeyCode('0x60', 96, '0', '"0" on the numeric keypad.'),
    NUMPAD1: new KeyCode('0x61', 97, '1', '"1" on the numeric keypad.'),
    NUMPAD2: new KeyCode('0x62', 98, '2', '"2" on the numeric keypad.'),
    NUMPAD3: new KeyCode('0x63', 99, '3', '"3" on the numeric keypad.'),
    NUMPAD4: new KeyCode('0x64', 100, '4', '"4" on the numeric keypad.'),
    NUMPAD5: new KeyCode('0x65', 101, '5', '"5" on the numeric keypad.'),
    NUMPAD6: new KeyCode('0x66', 102, '6 ', '"6" on the numeric keypad.'),
    NUMPAD7: new KeyCode('0x67', 103, '7', '"7" on the numeric keypad.'),
    NUMPAD8: new KeyCode('0x68', 104, '8', '"8" on the numeric keypad.'),
    NUMPAD9: new KeyCode('0x69', 105, '9', '"8" on the numeric keypad.'),
    MULTIPLY: new KeyCode('0x6A', 106, '*', 'The "*" key on the numeric keypad.'),
    ADD: new KeyCode('0x6B', 107, '+', 'The "+" key on the numeric keypad.'),
    // SEPARATOR - 108 - Not sure what key this maps to.
    SUBTRACT: new KeyCode('0x6D', 109, '-', 'The "-" key on the numeric keypad.'),
    DECIMAL: new KeyCode('0x6E', 110, '-', 'The decimal point on the numeric keypad.'),
    DIVIDE: new KeyCode('0x6F', 111, '-', 'The "/" key on the numeric keypad.'),

    // Function Keys
    F1: new KeyCode('0x70', 112, 'F1', 'The F1 key.'),
    F2: new KeyCode('0x71', 113, 'F2', 'The F2 key.'),
    F3: new KeyCode('0x72', 114, 'F3', 'The F3 key.'),
    F4: new KeyCode('0x73', 115, 'F4', 'The F4 key.'),
    F5: new KeyCode('0x74', 116, 'F5', 'The F5 key.'),
    F6: new KeyCode('0x75', 117, 'F6', 'The F6 key.'),
    F7: new KeyCode('0x76', 118, 'F7', 'The F7 key.'),
    F8: new KeyCode('0x77', 119, 'F8', 'The F8 key.'),
    F9: new KeyCode('0x78', 120, 'F9', 'The F9 key.'),
    F10: new KeyCode('0x79', 121, 'F10', 'The F10 key.'),
    F11: new KeyCode('0x7A', 122, 'F11', 'The F11 key.'),
    F12: new KeyCode('0x7B', 123, 'F12', 'The F12 key.'),
    F13: new KeyCode('0x7C', 124, 'F13', 'The F13 key.'),
    F14: new KeyCode('0x7D', 125, 'F14', 'The F14 key.'),
    F15: new KeyCode('0x7E', 126, 'F15', 'The F15 key.'),
    F16: new KeyCode('0x7F', 127, 'F16', 'The F16 key.'),
    F17: new KeyCode('0x80', 128, 'F17', 'The F17 key.'),
    F18: new KeyCode('0x81', 129, 'F18', 'The F18 key.'),
    F19: new KeyCode('0x82', 130, 'F19', 'The F19 key.'),
    F20: new KeyCode('0x83', 131, 'F20', 'The F20 key.'),
    F21: new KeyCode('0x84', 132, 'F21', 'The F21 key.'),
    F22: new KeyCode('0x85', 133, 'F22', 'The F22 key.'),
    F23: new KeyCode('0x86', 134, 'F23', 'The F23 key.'),
    F24: new KeyCode('0x87', 135, 'F24', 'The F24 key.'),

    NUM_LOCK: new KeyCode('0x90', 144, 'Num Lock', 'The Num Lock key.'),
    SCROLL_LOCK: new KeyCode('0x91', 145, 'Scroll Lock', 'The Scroll Lock key.'),

    // Fujitsu OASYS Specific Keys
    WIN_OEM_FJ_JISHO: new KeyCode('0x92', 146, 'Jisho', 'An OEM specific key on Windows. This was used for "Dictionary" key on Fujitsu OASYS.'),
    WIN_OEM_FJ_MASSHOU: new KeyCode('0x93', 147, 'Masshou', 'An OEM specific key on Windows. This was used for "Unregister word" key on Fujitsu OASYS.'),
    WIN_OEM_FJ_TOUROKU: new KeyCode('0x94', 148, 'Touroku', 'An OEM specific key on Windows. This was used for "Register word" key on Fujitsu OASYS.'),
    WIN_OEM_FJ_LOYA: new KeyCode('0x95', 149, 'Loya', 'An OEM specific key on Windows. This was used for "Left OYAYUBI" key on Fujitsu OASYS.'),
    WIN_OEM_FJ_ROYA: new KeyCode('0x96', 150, 'Roya', 'An OEM specific key on Windows. This was used for "Right OYAYUBI" key on Fujitsu OASYS.'),

    CIRCUMFLEX: new KeyCode('0xA0', 160, 'Circumflex', 'The circumflex (^) key.'),
    EXCLAMATION: new KeyCode('0xA1', 161, 'Exclamation', 'The exclamation (!) key.'),
    DOUBLE_QUOTE: new KeyCode('0xA2', 162, 'Double Quote', 'The double quote (") key.'),
    HASH: new KeyCode('0xA3', 163, 'Hash', 'The hash (#) key.'),
    DOLLAR: new KeyCode('0xA4', 164, 'Dollar Sign', 'The dollar sign ($) key.'),
    PERCENT: new KeyCode('0xA5', 165, 'Percent', 'The percent (%) key.'),
    AMPERSAND: new KeyCode('0xA6', 166, 'Ampersand', 'The ampersand (&) key.'),
    UNDERSCORE: new KeyCode('0xA7', 167, 'Underscore', 'The underscore (_) key.'),
    OPEN_PAREN: new KeyCode('0xA8', 168, 'Open Paren', 'The open paren (() key.'),
    CLOSE_PAREN: new KeyCode('0xA9', 169, 'Close Paren', 'The close paren ()) key.'),
    ASTERISK: new KeyCode('0xAA', 170, 'Asterisk', 'The asterisk (*) key.'),
    PLUS: new KeyCode('0xAB', 171, 'Plus', 'The plus (+) key.'),
    PIPE: new KeyCode('0xAC', 172, 'Asterisk', 'The asterisk (*) key.'),
    HYPHEN_MINUS: new KeyCode('0xAD', 173, 'Hyphen/Minus', 'The hyphen or minus (-) key.'),
    OPEN_CURLY_BRACKET: new KeyCode('0xAE', 174, 'Open Bracket', 'The open bracket ({) key.'),
    CLOSE_CURLY_BRACKET: new KeyCode('0xAF', 175, 'Close Bracket', 'The close bracket (}) key.'),
    TILDE: new KeyCode('0xB0', 176, 'Tilde', 'The tilde (~) key.'),

    // Volume Keys
    VOLUME_MUTE: new KeyCode('0xB5', 181, 'Volume Mute', 'The audio mute key.'),
    VOLUME_DOWN: new KeyCode('0xB6', 182, 'Volume Down', 'The audio volume down key.'),
    VOLUME_UP: new KeyCode('0xB7', 183, 'Volume Up', 'The audio volume up key.'),

    PERIOD: new KeyCode('0xBE', 190, 'Period', 'The period key.'),
    SLASH: new KeyCode('0xBF', 191, 'Slash', 'The slash key.'),
    BACK_QUOTE: new KeyCode('0xC0', 192, '`', 'The back tick (`) key.'),
    OPEN_BRACKET: new KeyCode('0xDB', 219, '[', 'The open bracket ([) key.'),
    BACK_SLASH: new KeyCode('0xDC', 220, '\\', 'The backslash (\\) key.'),
    CLOSE_BRACKET: new KeyCode('0xDD', 221, ']', 'The close bracket (]) key.'),
    QUOTE: new KeyCode('0xDE', 222, '\'', 'The quote (\') key.'),

    META: new KeyCode('0xE0', 224, 'Meta', 'The meta key on Linux, or Command on Mac.'),
    COMMAND: new KeyCode('0xE0', 224, 'Command', 'The meta key on Linux, or Command on Mac.'),
    ALTGR: new KeyCode('0xE1', 225, 'AltGr', 'The AltGr key (Level 3 Shift key or LEvel 5 Shift key) on Linux.'),

    // Olivetti ICO Keys
    WIN_ICO_HELP: new KeyCode('0xE3', 227, 'ICO Help'),
    WIN_ICO_00: new KeyCode('0xE4', 228, 'ICO 00'),
    WIN_ICO_CLEAR: new KeyCode('0xE6', 230, 'ICO Clear'),

    // Nokia/Ericsson Keys
    WIN_OEM_RESET: new KeyCode('0xE9', 233, 'OEM Reset'),
    WIN_OEM_JUMP: new KeyCode('0xEA', 234, 'OEM Jump'),
    WIN_OEM_PA1: new KeyCode('0xEB', 235, 'OEM PA1'),
    WIN_OEM_PA2: new KeyCode('0xEC', 236, 'OEM PA2'),
    WIN_OEM_PA3: new KeyCode('0xED', 237, 'OEM PA3'),
    WIN_OEM_WSCTRL: new KeyCode('0xEE', 238, 'OEM WSCTRL'),
    WIN_OEM_CUSEL: new KeyCode('0xEF', 239, 'OEM CUSEL'),
    WIN_OEM_ATTN: new KeyCode('0xF0', 240, 'OEM ATTN'),
    WIN_OEM_FINISH: new KeyCode('0xF1', 241, 'OEM FINISH'),
    WIN_OEM_COPY: new KeyCode('0xF2', 242, 'OEM COPY'),
    WIN_OEM_AUTO: new KeyCode('0xF3', 243, 'OEM AUTO'),
    WIN_OEM_ENLW: new KeyCode('0xF4', 244, 'OEM ENLW'),
    WIN_OEM_BACKTAB: new KeyCode('0xF5', 245, 'OEM BACK TAB'),

    ATTN: new KeyCode('0xF6', 246, 'Attn', 'Attn (Attention) key of IBM midrange computers, e.g., AS/400.'),
    CRSEL: new KeyCode('0xF7', 247, 'CrSel', 'CrSel (Cursor Selection) key of IBM 3270 keyboard layout.'),
    EXSEL: new KeyCode('0xF8', 248, 'ExSel', 'ExSel (Extend Selection) key of IBM 3270 keyboard layout.'),
    EREOF: new KeyCode('0xF9', 249, 'Erase EOF', 'Erase EOF key of IBM 3270 keyboard layout.'),
    PLAY: new KeyCode('0xFA', 250, 'Play', 'Play key of IBM 3270 keyboard layout.'),
    ZOOM: new KeyCode('0xFB', 251, 'Zoom', 'The Zoom key.'),
    PA1: new KeyCode('0xFD', 253, 'PA1', 'The PA1 key of IBM 3270 keyboard layout.'),
    WIN_OEM_CLEAR: new KeyCode('0xFE', 254, 'Clear', 'The Clear key on Windows.'),
}

export default keyCodes;